# Analyzing tabular data with python

In [2]:
import pandas as pd
import os

In [3]:
os.listdir("./data")

['sample', 'sample_covid_data.csv', 'sample_covid_data2_with_nan.csv']

In [4]:
covid_df = pd.read_csv("./data/sample_covid_data.csv")

In [5]:
type(covid_df)

pandas.core.frame.DataFrame

In [6]:
covid_df

            date  new_cases  new_deaths  new_tests
0     2020-01-01       2063          20      15712
1     2020-01-02        576          28       2992
2     2020-01-03       2264          35       5109
3     2020-01-04       3379         100       4556
4     2020-01-05       4037          47      13630
...          ...        ...         ...        ...
9995  2047-05-14       3928          99       9911
9996  2047-05-15       2936          65       5734
9997  2047-05-16       1628          20       9749
9998  2047-05-17        221          11       9875
9999  2047-05-18       2945          22      16164

[10000 rows x 4 columns]

We can get some information about our DataFrame using the info() function

In [7]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        10000 non-null  object
 1   new_cases   10000 non-null  int64
 2   new_deaths  10000 non-null  int64
 3   new_tests   10000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 312.6+ KB

WE can see there are 10000 values firn 0 to 9999 columns and non of them is a non null count as we can see clearly

In [8]:
covid_df2 = pd.read_csv("./data/sample_covid_data2_with_nan.csv")

In [9]:
covid_df2

            date  new_cases  new_deaths  new_tests
0     2020-01-01       3287          14    16661.0
1     2020-01-02       3150          16     7128.0
2     2020-01-03       4363           3    18559.0
3     2020-01-04       2316          31    17568.0
4     2020-01-05       1873           5     9866.0
...          ...        ...         ...        ...
9995  2047-05-14       2035           7     9164.0
9996  2047-05-15       2675          71     7051.0
9997  2047-05-16        986          15    10943.0
9998  2047-05-17       3146          53    19207.0
9999  2047-05-18       2598          33    12564.0

[10000 rows x 4 columns]

In [10]:
covid_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        10000 non-null  object
 1   new_cases   10000 non-null  int64
 2   new_deaths  10000 non-null  int64
 3   new_tests   9188 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 312.6+ KB

Here we can see some NaN values

In [11]:
covid_df2.describe()

          new_cases    new_deaths     new_tests
count  10000.000000  10000.000000   9188.000000
mean    2516.862900     39.903800  11249.258598
std     1441.478861     28.977759   5083.580745
min        0.000000      0.000000    148.000000
25%     1257.000000     14.000000   7031.750000
50%     2525.500000     35.000000  11385.500000
75%     3767.250000     63.000000  15558.250000
max     5000.000000    100.000000  19999.000000

We can see more information like baove by using .describe() function

The column property contains the list of columns with the data frame.

In [12]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [13]:
covid_df.shape # This will give you shape but as a tuple

(10000, 4)

#### This was the way to get some information form the data

## Retrieving data form a data frame

df are conceptually like a dictnory of lists but actually it is a different datastructure of itself but we can access values using keys

In [14]:
covid_df2['new_cases']

0       3287
1       3150
2       4363
3       2316
4       1873
        ...
9995    2035
9996    2675
9997     986
9998    3146
9999    2598
Name: new_cases, Length: 10000, dtype: int64

Here each column is a data_structure called series which is essentially a numpy array but with some more benifits

In [15]:
type(covid_df["new_cases"])

pandas.core.series.Series

In [16]:
covid_df2["new_cases"][9996] # We can verify this form above

np.int64(2675)

In [17]:
covid_df2.at[9999, "new_cases"]

np.int64(2598)

instead of using indexing keys we can use colums as direct property of df ```
covid_df["new_cases"] = covid_df.new_cases ```

#### If you want to access multiple columns you can pass a list of columns 
for example

In [18]:
cases_df = covid_df2[['date','new_cases']]
cases_df

            date  new_cases
0     2020-01-01       3287
1     2020-01-02       3150
2     2020-01-03       4363
3     2020-01-04       2316
4     2020-01-05       1873
...          ...        ...
9995  2047-05-14       2035
9996  2047-05-15       2675
9997  2047-05-16        986
9998  2047-05-17       3146
9999  2047-05-18       2598

[10000 rows x 2 columns]

## Remember this data is pointing to the same data_frame in the memory even though it is just a part of the data hence if we modify this data it will make changes to the original data

In [19]:
covid_df2_copy = covid_df.copy()

In [20]:
covid_df2.loc[243]

date          2020-08-31
new_cases             16
new_deaths             0
new_tests            NaN
Name: 243, dtype: object

In [21]:
covid_df2.head(4)

         date  new_cases  new_deaths  new_tests
0  2020-01-01       3287          14    16661.0
1  2020-01-02       3150          16     7128.0
2  2020-01-03       4363           3    18559.0
3  2020-01-04       2316          31    17568.0

In [22]:
covid_df2.tail(4)

            date  new_cases  new_deaths  new_tests
9996  2047-05-15       2675          71     7051.0
9997  2047-05-16        986          15    10943.0
9998  2047-05-17       3146          53    19207.0
9999  2047-05-18       2598          33    12564.0

The following code is to check where we can find a first valid number, not a NaN in a specific column

in My case it is the first row only so it gives me zero

In [23]:
covid_df2.new_tests.first_valid_index()

0

In [24]:
covid_df2.loc[11:57]

          date  new_cases  new_deaths  new_tests
11  2020-01-12       4626          91    16511.0
12  2020-01-13       3382          35     8168.0
13  2020-01-14       4041           1    13993.0
14  2020-01-15         22           0     7865.0
15  2020-01-16       2276          32     7674.0
16  2020-01-17       2067          24    15208.0
17  2020-01-18       4644          18        NaN
18  2020-01-19       1251          12     4973.0
19  2020-01-20       4307           1    17206.0
20  2020-01-21        107           5    17868.0
21  2020-01-22       3094          55     8755.0
22  2020-01-23       4699          52    16239.0
23  2020-01-24       2010          54    11528.0
24  2020-01-25       2185          73     8875.0
25  2020-01-26       4892          99    12619.0
26  2020-01-27       2425          12        NaN
27  2020-01-28         92           3    14655.0
28  2020-01-29        645          13    11929.0
29  2020-01-30        555           4     7458.0
30  2020-01-31        706          29     7728.0
31  2020-02-01       5000          58     9138.0
32  2020-02-02        830          10    16765.0
33  2020-02-03       1336          50     7312.0
34  2020-02-04       1642          36    12181.0
35  2020-02-05       2252           9     9929.0
36  2020-02-06       2972          39     6186.0
37  2020-02-07       4815          82    14474.0
38  2020-02-08       1235          53    13804.0
39  2020-02-09       3464          98    11560.0
40  2020-02-10       4408          15    11973.0
41  2020-02-11       4244          35        NaN
42  2020-02-12        597          12     3071.0
43  2020-02-13       2108          58     8041.0
44  2020-02-14        904          36     4824.0
45  2020-02-15       2256          65    15048.0
46  2020-02-16         78           2    18279.0
47  2020-02-17       2865          38    10180.0
48  2020-02-18       2345          64    11183.0
49  2020-02-19       4738          80    14377.0
50  2020-02-20       1400           8    16080.0
51  2020-02-21        185           3    15266.0
52  2020-02-22       3775          21    15679.0
53  2020-02-23       4348          51     6372.0
54  2020-02-24       4348          30     5096.0
55  2020-02-25       2794          50     5248.0
56  2020-02-26       2260          89     4576.0
57  2020-02-27       1905          62     8576.0

In [25]:
covid_df2.sample(10)

            date  new_cases  new_deaths  new_tests
2417  2026-08-14       4392          16     6741.0
7813  2041-05-23        744          15     7446.0
6981  2039-02-11       1211           5     6321.0
6081  2036-08-25        564          13    18178.0
6866  2038-10-19       1829          75    19833.0
5741  2035-09-20        368           9     6403.0
6377  2037-06-17       2076          78    12168.0
5851  2036-01-08       3942           7    17859.0
3866  2030-08-02       2089          20    13474.0
2660  2027-04-14       2665          94     3575.0

# Analyzing data form data frames 
Till now we are done with basics of pandas now we can move on to analyze the data and finding out revelent and figuering our revelent information.

In [26]:
total_cases = covid_df.new_cases.sum()
total_deaths = covid_df.new_deaths.sum()

In [27]:
print('The number of reportd cases is {} and the number of reported deaths{}'.format(total_cases, total_deaths))

The number of reportd cases is 24950091 and the number of reported deaths436102

*What is the overall number of tests conducted? A total of 935310 tests were conducted before daily test number being reported*

In [28]:
initial_tests = 935310
total_tests = initial_tests + covid_df2.new_tests.sum()

In [29]:
total_tests

np.float64(104293498.0)

In [30]:
positive_rate = total_cases / total_tests

In [33]:
print('{:.2f}% of tests in Italy led to positive diagonsis.'.format(positive_rate))

0.24% of tests in Italy led to positive diagonsis.

In [34]:
high_new_cases = covid_df.new_cases > 1000

In [35]:
high_new_cases

0        True
1       False
2        True
3        True
4        True
        ...
9995     True
9996     True
9997     True
9998    False
9999     True
Name: new_cases, Length: 10000, dtype: bool

In [37]:
high_cases_df = covid_df2[covid_df2.new_cases > 1000]

In [39]:
covid_df[high_new_cases]

            date  new_cases  new_deaths  new_tests
0     2020-01-01       2063          20      15712
2     2020-01-03       2264          35       5109
3     2020-01-04       3379         100       4556
4     2020-01-05       4037          47      13630
5     2020-01-06       2545          89       8995
...          ...        ...         ...        ...
9994  2047-05-13       4729           0      16112
9995  2047-05-14       3928          99       9911
9996  2047-05-15       2936          65       5734
9997  2047-05-16       1628          20       9749
9999  2047-05-18       2945          22      16164

[7993 rows x 4 columns]

In [38]:
high_cases_df

            date  new_cases  new_deaths  new_tests
0     2020-01-01       3287          14    16661.0
1     2020-01-02       3150          16     7128.0
2     2020-01-03       4363           3    18559.0
3     2020-01-04       2316          31    17568.0
4     2020-01-05       1873           5     9866.0
...          ...        ...         ...        ...
9994  2047-05-13       4265          29    12758.0
9995  2047-05-14       2035           7     9164.0
9996  2047-05-15       2675          71     7051.0
9998  2047-05-17       3146          53    19207.0
9999  2047-05-18       2598          33    12564.0

[8078 rows x 4 columns]