# Analyzing tabular data with python

In [2]:
import pandas as pd
import os

In [3]:
os.listdir("./data")

['sample', 'sample_covid_data.csv', 'sample_covid_data2_with_nan.csv']

In [4]:
covid_df = pd.read_csv("./data/sample_covid_data.csv")

In [5]:
type(covid_df)

pandas.core.frame.DataFrame

In [6]:
covid_df

            date  new_cases  new_deaths  new_tests
0     2020-01-01       2063          20      15712
1     2020-01-02        576          28       2992
2     2020-01-03       2264          35       5109
3     2020-01-04       3379         100       4556
4     2020-01-05       4037          47      13630
...          ...        ...         ...        ...
9995  2047-05-14       3928          99       9911
9996  2047-05-15       2936          65       5734
9997  2047-05-16       1628          20       9749
9998  2047-05-17        221          11       9875
9999  2047-05-18       2945          22      16164

[10000 rows x 4 columns]

We can get some information about our DataFrame using the info() function

In [7]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        10000 non-null  object
 1   new_cases   10000 non-null  int64
 2   new_deaths  10000 non-null  int64
 3   new_tests   10000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 312.6+ KB

WE can see there are 10000 values firn 0 to 9999 columns and non of them is a non null count as we can see clearly

In [8]:
covid_df2 = pd.read_csv("./data/sample_covid_data2_with_nan.csv")

In [9]:
covid_df2

            date  new_cases  new_deaths  new_tests
0     2020-01-01       3287          14    16661.0
1     2020-01-02       3150          16     7128.0
2     2020-01-03       4363           3    18559.0
3     2020-01-04       2316          31    17568.0
4     2020-01-05       1873           5     9866.0
...          ...        ...         ...        ...
9995  2047-05-14       2035           7     9164.0
9996  2047-05-15       2675          71     7051.0
9997  2047-05-16        986          15    10943.0
9998  2047-05-17       3146          53    19207.0
9999  2047-05-18       2598          33    12564.0

[10000 rows x 4 columns]

In [10]:
covid_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        10000 non-null  object
 1   new_cases   10000 non-null  int64
 2   new_deaths  10000 non-null  int64
 3   new_tests   9188 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 312.6+ KB

Here we can see some NaN values

In [11]:
covid_df2.describe()

          new_cases    new_deaths     new_tests
count  10000.000000  10000.000000   9188.000000
mean    2516.862900     39.903800  11249.258598
std     1441.478861     28.977759   5083.580745
min        0.000000      0.000000    148.000000
25%     1257.000000     14.000000   7031.750000
50%     2525.500000     35.000000  11385.500000
75%     3767.250000     63.000000  15558.250000
max     5000.000000    100.000000  19999.000000

We can see more information like baove by using .describe() function

The column property contains the list of columns with the data frame.

In [12]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [13]:
covid_df.shape # This will give you shape but as a tuple

(10000, 4)

#### This was the way to get some information form the data

## Retrieving data form a data frame

df are conceptually like a dictnory of lists but actually it is a different datastructure of itself but we can access values using keys

In [14]:
covid_df2['new_cases']

0       3287
1       3150
2       4363
3       2316
4       1873
        ...
9995    2035
9996    2675
9997     986
9998    3146
9999    2598
Name: new_cases, Length: 10000, dtype: int64

Here each column is a data_structure called series which is essentially a numpy array but with some more benifits

In [15]:
type(covid_df["new_cases"])

pandas.core.series.Series

In [16]:
covid_df2["new_cases"][9996] # We can verify this form above

np.int64(2675)

In [17]:
covid_df2.at[9999, "new_cases"]

np.int64(2598)

instead of using indexing keys we can use colums as direct property of df ```
covid_df["new_cases"] = covid_df.new_cases ```

#### If you want to access multiple columns you can pass a list of columns 
for example

In [18]:
cases_df = covid_df2[['date','new_cases']]
cases_df

            date  new_cases
0     2020-01-01       3287
1     2020-01-02       3150
2     2020-01-03       4363
3     2020-01-04       2316
4     2020-01-05       1873
...          ...        ...
9995  2047-05-14       2035
9996  2047-05-15       2675
9997  2047-05-16        986
9998  2047-05-17       3146
9999  2047-05-18       2598

[10000 rows x 2 columns]

## Remember this data is pointing to the same data_frame in the memory even though it is just a part of the data hence if we modify this data it will make changes to the original data

In [19]:
covid_df2_copy = covid_df.copy()

In [20]:
covid_df2.loc[243]

date          2020-08-31
new_cases             16
new_deaths             0
new_tests            NaN
Name: 243, dtype: object

In [21]:
covid_df2.head(4)

         date  new_cases  new_deaths  new_tests
0  2020-01-01       3287          14    16661.0
1  2020-01-02       3150          16     7128.0
2  2020-01-03       4363           3    18559.0
3  2020-01-04       2316          31    17568.0

In [22]:
covid_df2.tail(4)

            date  new_cases  new_deaths  new_tests
9996  2047-05-15       2675          71     7051.0
9997  2047-05-16        986          15    10943.0
9998  2047-05-17       3146          53    19207.0
9999  2047-05-18       2598          33    12564.0

The following code is to check where we can find a first valid number, not a NaN in a specific column

in My case it is the first row only so it gives me zero

In [23]:
covid_df2.new_tests.first_valid_index()

0

In [24]:
covid_df2.loc[11:57]

          date  new_cases  new_deaths  new_tests
11  2020-01-12       4626          91    16511.0
12  2020-01-13       3382          35     8168.0
13  2020-01-14       4041           1    13993.0
14  2020-01-15         22           0     7865.0
15  2020-01-16       2276          32     7674.0
16  2020-01-17       2067          24    15208.0
17  2020-01-18       4644          18        NaN
18  2020-01-19       1251          12     4973.0
19  2020-01-20       4307           1    17206.0
20  2020-01-21        107           5    17868.0
21  2020-01-22       3094          55     8755.0
22  2020-01-23       4699          52    16239.0
23  2020-01-24       2010          54    11528.0
24  2020-01-25       2185          73     8875.0
25  2020-01-26       4892          99    12619.0
26  2020-01-27       2425          12        NaN
27  2020-01-28         92           3    14655.0
28  2020-01-29        645          13    11929.0
29  2020-01-30        555           4     7458.0
30  2020-01-31        706          29     7728.0
31  2020-02-01       5000          58     9138.0
32  2020-02-02        830          10    16765.0
33  2020-02-03       1336          50     7312.0
34  2020-02-04       1642          36    12181.0
35  2020-02-05       2252           9     9929.0
36  2020-02-06       2972          39     6186.0
37  2020-02-07       4815          82    14474.0
38  2020-02-08       1235          53    13804.0
39  2020-02-09       3464          98    11560.0
40  2020-02-10       4408          15    11973.0
41  2020-02-11       4244          35        NaN
42  2020-02-12        597          12     3071.0
43  2020-02-13       2108          58     8041.0
44  2020-02-14        904          36     4824.0
45  2020-02-15       2256          65    15048.0
46  2020-02-16         78           2    18279.0
47  2020-02-17       2865          38    10180.0
48  2020-02-18       2345          64    11183.0
49  2020-02-19       4738          80    14377.0
50  2020-02-20       1400           8    16080.0
51  2020-02-21        185           3    15266.0
52  2020-02-22       3775          21    15679.0
53  2020-02-23       4348          51     6372.0
54  2020-02-24       4348          30     5096.0
55  2020-02-25       2794          50     5248.0
56  2020-02-26       2260          89     4576.0
57  2020-02-27       1905          62     8576.0

In [25]:
covid_df2.sample(10)

            date  new_cases  new_deaths  new_tests
195   2020-07-14        714          13     4975.0
3653  2030-01-01       2242          22     7627.0
1430  2023-12-01        490           8     4299.0
5854  2036-01-11        640          32     5644.0
6294  2037-03-26        807          19     1425.0
2295  2026-04-14       4891           3    10477.0
3439  2029-06-01       2535          55     5214.0
5643  2035-06-14       1409          27    14039.0
9808  2046-11-08       3828          61    15564.0
4001  2030-12-15       2456          39     3533.0

# Analyzing data form data frames 
Till now we are done with basics of pandas now we can move on to analyze the data and finding out revelent and figuering our revelent information.

In [26]:
total_cases = covid_df.new_cases.sum()
total_deaths = covid_df.new_deaths.sum()

In [27]:
print('The number of reportd cases is {} and the number of reported deaths{}'.format(total_cases, total_deaths))

The number of reportd cases is 24950091 and the number of reported deaths436102

*What is the overall number of tests conducted? A total of 935310 tests were conducted before daily test number being reported*

In [28]:
initial_tests = 935310
total_tests = initial_tests + covid_df2.new_tests.sum()

In [29]:
total_tests

np.float64(104293498.0)

In [30]:
positive_rate = total_cases / total_tests

In [31]:
print('{:.2f}% of tests in Italy led to positive diagonsis.'.format(positive_rate))

0.24% of tests in Italy led to positive diagonsis.

In [39]:
high_new_cases = covid_df2.new_cases > 1000

In [40]:
high_new_cases

0        True
1        True
2        True
3        True
4        True
        ...
9995     True
9996     True
9997    False
9998     True
9999     True
Name: new_cases, Length: 10000, dtype: bool

As we can see this have given us a series which have true and false according where the system is getting satisfied.

now we can pass this in to df as idex so we can get only rows thich were true

In [41]:
covid_df2[high_new_cases]

            date  new_cases  new_deaths  new_tests
0     2020-01-01       3287          14    16661.0
1     2020-01-02       3150          16     7128.0
2     2020-01-03       4363           3    18559.0
3     2020-01-04       2316          31    17568.0
4     2020-01-05       1873           5     9866.0
...          ...        ...         ...        ...
9994  2047-05-13       4265          29    12758.0
9995  2047-05-14       2035           7     9164.0
9996  2047-05-15       2675          71     7051.0
9998  2047-05-17       3146          53    19207.0
9999  2047-05-18       2598          33    12564.0

[8078 rows x 4 columns]

In [44]:
high_cases_df = covid_df2[covid_df2.new_cases > 1000]

In [45]:
high_cases_df

            date  new_cases  new_deaths  new_tests
0     2020-01-01       3287          14    16661.0
1     2020-01-02       3150          16     7128.0
2     2020-01-03       4363           3    18559.0
3     2020-01-04       2316          31    17568.0
4     2020-01-05       1873           5     9866.0
...          ...        ...         ...        ...
9994  2047-05-13       4265          29    12758.0
9995  2047-05-14       2035           7     9164.0
9996  2047-05-15       2675          71     7051.0
9998  2047-05-17       3146          53    19207.0
9999  2047-05-18       2598          33    12564.0

[8078 rows x 4 columns]

The data contains 8078 rows but only first and last 5 are visiable by default. to view all the rows, we can modify some display options

In [51]:
from IPython.display import display

with pd.option_context('display.max_rows', 100):
    display(covid_df[covid_df.new_cases > 1000])

            date  new_cases  new_deaths  new_tests
0     2020-01-01       2063          20      15712
2     2020-01-03       2264          35       5109
3     2020-01-04       3379         100       4556
4     2020-01-05       4037          47      13630
5     2020-01-06       2545          89       8995
...          ...        ...         ...        ...
9994  2047-05-13       4729           0      16112
9995  2047-05-14       3928          99       9911
9996  2047-05-15       2936          65       5734
9997  2047-05-16       1628          20       9749
9999  2047-05-18       2945          22      16164

[7993 rows x 4 columns]

The above code is not showing the hundread lines because.```display.max_rows``` This only sets the maximum number of rows that Pandas is allowed to display. To see atleast 100 we have to set ```display.min_rows``` as 100

In [52]:
from IPython.display import display

with pd.option_context(
    'display.max_rows', 100,
    'display.min_rows', 100
):
    display(covid_df[covid_df.new_cases > 1000])

            date  new_cases  new_deaths  new_tests
0     2020-01-01       2063          20      15712
2     2020-01-03       2264          35       5109
3     2020-01-04       3379         100       4556
4     2020-01-05       4037          47      13630
5     2020-01-06       2545          89       8995
7     2020-01-08       3194          24       6801
8     2020-01-09       1647          29      13511
11    2020-01-12       3065          92       9409
12    2020-01-13       1183          59       5346
13    2020-01-14       4757          50      11502
14    2020-01-15       1021          51      14926
17    2020-01-18       4665          62      17515
18    2020-01-19       1696          42       9897
19    2020-01-20       3463          88       7424
20    2020-01-21       4045          43       5806
21    2020-01-22       4831          84       6503
22    2020-01-23       4064          65       9176
23    2020-01-24       3834           4      19555
25    2020-01-26       1424          61       2480
26    2020-01-27       4775          84      10110
27    2020-01-28       1388          52      16296
29    2020-01-30       1180          59      11486
30    2020-01-31       3737          23      16833
31    2020-02-01       3493          35      18834
33    2020-02-03       2036          46      18561
34    2020-02-04       4777          62      14797
35    2020-02-05       2217          86      15230
37    2020-02-07       2283          99       4917
38    2020-02-08       3526          60      13048
39    2020-02-09       4935          91      16124
40    2020-02-10       1116          55       5495
41    2020-02-11       2402          75      10640
43    2020-02-13       4463          17      18107
44    2020-02-14       2064          97      15843
45    2020-02-15       2414          19      18457
47    2020-02-17       4192          83       4807
48    2020-02-18       4746          47      14256
49    2020-02-19       4300           4      11550
51    2020-02-21       1827          22       6676
53    2020-02-23       4558          72      17542
54    2020-02-24       4169          60      18241
55    2020-02-25       1094          18      15279
58    2020-02-28       3925           3      15403
59    2020-02-29       3776          74       8249
60    2020-03-01       3646           8       7316
61    2020-03-02       2402          56       3407
62    2020-03-03       1792          89       2040
63    2020-03-04       4705          41      11919
64    2020-03-05       4809          12       7803
65    2020-03-06       4848          54      19718
...          ...        ...         ...        ...
9934  2047-03-14       2956          82      10208
9935  2047-03-15       4598          89      17485
9936  2047-03-16       2291          58      17111
9937  2047-03-17       1229          61       2834
9938  2047-03-18       1464          38       2306
9942  2047-03-22       2417          50       5049
9943  2047-03-23       2760           5       6704
9944  2047-03-24       4351          68      14561
9945  2047-03-25       4246          29      14867
9946  2047-03-26       3387          78      14881
9947  2047-03-27       4537          53      16116
9949  2047-03-29       4182          68      17225
9950  2047-03-30       1916          34       9128
9951  2047-03-31       2384          13      10389
9953  2047-04-02       4386          84      12849
9954  2047-04-03       3905          75       4661
9955  2047-04-04       1143          39       7259
9956  2047-04-05       3252          86       6659
9957  2047-04-06       4012          96      12642
9958  2047-04-07       2770           8       8310
9960  2047-04-09       1701          46       9528
9961  2047-04-10       3800          22       4194
9962  2047-04-11       1216          60       3084
9965  2047-04-14       3616          93      14875
9966  2047-04-15       2265          83      10662
9967  2047-04-16       2102           5       5853
9968  2047-04-17       3815          53      19964
9970  2047-04-19       2238          59      11138
9972  2047-04-21       2427          90       4419
9973  2047-04-22       1990          28      18390
9974  2047-04-23       4326          29      14115
9975  2047-04-24       1098          54       9628
9977  2047-04-26       4215          20       7750
9978  2047-04-27       1766          37      19871
9979  2047-04-28       4562          29      15575
9981  2047-04-30       2826          46      13100
9982  2047-05-01       3723          71      15147
9983  2047-05-02       3970          16       7181
9984  2047-05-03       3011          33      18040
9985  2047-05-04       3216           7      18957
9986  2047-05-05       4975           6      13134
9988  2047-05-07       1941          64       8471
9989  2047-05-08       3495          28      19539
9990  2047-05-09       1665          15       6970
9992  2047-05-11       3921          21       8233
9994  2047-05-13       4729           0      16112
9995  2047-05-14       3928          99       9911
9996  2047-05-15       2936          65       5734
9997  2047-05-16       1628          20       9749
9999  2047-05-18       2945          22      16164

[7993 rows x 4 columns]

In [ ]:
positive_rate # This shows what percentage of cases turned out to be positive in compression to all of them

np.float64(0.23922959224169468)

In [54]:
high_ratio_df = covid_df[covid_df.new_cases / covid_df.new_tests > positive_rate]

Here we are dividing a series by series. This will give you element wise divisions.

In [55]:
high_ratio_df

            date  new_cases  new_deaths  new_tests
2     2020-01-03       2264          35       5109
3     2020-01-04       3379         100       4556
4     2020-01-05       4037          47      13630
5     2020-01-06       2545          89       8995
7     2020-01-08       3194          24       6801
...          ...        ...         ...        ...
9986  2047-05-05       4975           6      13134
9992  2047-05-11       3921          21       8233
9994  2047-05-13       4729           0      16112
9995  2047-05-14       3928          99       9911
9996  2047-05-15       2936          65       5734

[4767 rows x 4 columns]

this will give you a new series where ratio of new cases were higher then the new tests.

**Further you can us this series to add a new column to the data frame.**

In [58]:
covid_df2["positive_rate"] = covid_df2.new_cases / covid_df2.new_tests

In [59]:
covid_df2

            date  new_cases  new_deaths  new_tests  positive_rate
0     2020-01-01       3287          14    16661.0       0.197287
1     2020-01-02       3150          16     7128.0       0.441919
2     2020-01-03       4363           3    18559.0       0.235088
3     2020-01-04       2316          31    17568.0       0.131831
4     2020-01-05       1873           5     9866.0       0.189844
...          ...        ...         ...        ...            ...
9995  2047-05-14       2035           7     9164.0       0.222065
9996  2047-05-15       2675          71     7051.0       0.379379
9997  2047-05-16        986          15    10943.0       0.090103
9998  2047-05-17       3146          53    19207.0       0.163794
9999  2047-05-18       2598          33    12564.0       0.206781

[10000 rows x 5 columns]

In [66]:
covid_df2.drop(columns=["positive_rate"], inplace=True, errors= "ignore") # This will remove the column form the dataset

In [67]:
covid_df2

            date  new_cases  new_deaths  new_tests
0     2020-01-01       3287          14    16661.0
1     2020-01-02       3150          16     7128.0
2     2020-01-03       4363           3    18559.0
3     2020-01-04       2316          31    17568.0
4     2020-01-05       1873           5     9866.0
...          ...        ...         ...        ...
9995  2047-05-14       2035           7     9164.0
9996  2047-05-15       2675          71     7051.0
9997  2047-05-16        986          15    10943.0
9998  2047-05-17       3146          53    19207.0
9999  2047-05-18       2598          33    12564.0

[10000 rows x 4 columns]

## Sorting rows using column values 
The rows can also be sorted by a specific column using .sort_values. Let's sort to identify the days with the highest number of cases, then chain it with the head method wo get the days with the most cases.

In [69]:
covid_df.sort_values("new_cases", ascending=False).head(10)

            date  new_cases  new_deaths  new_tests
5241  2034-05-08       5000          10       7776
7858  2041-07-07       5000          83      19598
4045  2031-01-28       5000          52      11187
6499  2037-10-17       4999          98      10865
7175  2039-08-24       4998          75      10165
6725  2038-05-31       4997          52      19366
3411  2029-05-04       4997          35      10275
2432  2026-08-29       4996          22      10276
83    2020-03-24       4995          16      15014
3325  2029-02-07       4995          12      14940

Showing perameter info (While the cursore is inside that function)
1. Jupyter Shift + Tab
2. VS Code Ctrl + Shift + Space

In [70]:
covid_df2.sort_values("new_cases").head(10)

            date  new_cases  new_deaths  new_tests
557   2021-07-11          0           0        NaN
4860  2033-04-22          0           0     7886.0
3415  2029-05-08          0           0    11701.0
64    2020-03-05          0           0        NaN
4558  2032-06-24          1           0    19559.0
4158  2031-05-21          1           0    15129.0
3243  2028-11-17          1           0    11845.0
5337  2034-08-12          2           0    19810.0
9508  2046-01-12          2           0    15106.0
6654  2038-03-21          3           0        NaN